apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  type: ClusterIP
  ports:
    - targetPort: 27017
      port: 27017
      name: port1
    - targetPort: 8081
      port: 8081
      name: port2
  selector:
    app: mongo